# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andreas Garnæs
tagline:          
url:              https://andreas.github.io/
paginate:         5
baseurl:          /
author:
  name:           Andreas Garnæs
  url:            https://twitter.com/cuvius
  email:          andreas.garnaes@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/andreas

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
